version: '3'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,apigateway,lambda,cloudformation,sts,iam
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./.localstack:/tmp/localstack
    ports:
      - 4566:4566
